package ledgrid

import (
	"fmt"
	"image"
	"log"
	"os"

	"golang.org/x/image/font/basicfont"
)

const (
	numGlyphs = 95
)

var (
	// ' ' ! " # $ % & ' ( ) * + , - . /  (16 Glyphs)
	rangePunct1 = basicfont.Range{'\u0020', '\u0030', 0}
    numPunct1 = 16

	// '0'-'9'                            (10 Glyphs: the decimal digits)
	rangeDigits = basicfont.Range{'\u0030', '\u003a', 0}
    numDigits = 10

	// ':' ';' '<' '=' '>' '?' '@'        (7 Glyphs)
	rangePunct2 = basicfont.Range{'\u003a', '\u0041', 0}
    numPunct2 = 7

	// 'A'-'Z'                            (26 Glyphs: lowercase characters)
	rangeUpper = basicfont.Range{'\u0041', '\u005b', 0}
    numUpper = 26

	// '[' '\' ']' '^' '_' '`'            (6 Glyphs)
	rangePunct3 = basicfont.Range{'\u005b', '\u0061', 0}
    numPunct3 = 6

	// 'a'-'z'                            (26 Glyphs: uppercase characters)
	rangeLower = basicfont.Range{'\u0061', '\u007b', 0}
    numLower = 26

	// '{' '|' '}' '~'                    (4 Glyphs)
	rangePunct4 = basicfont.Range{'\u007b', '\u007f', 0}
    numPunct4 = 4

	glyphRangeFull = []basicfont.Range{
		{'\u0020', '\u007f', 0},
	}
)

// This function can be used to produce a new fixed font by scaling an existing
// fixed font. Scaling factors can only be positive integers. The new font
// is
func ScaleFixedFont(face *basicfont.Face, factor int, newName string) {
	width := face.Width
	height := face.Ascent
	mask := face.Mask.(*image.Alpha)
	fileName := fmt.Sprintf("font%s.go", newName)
	fh, err := os.Create(fileName)
	if err != nil {
		log.Fatalf("Couldn't create file: %v", err)
	}
	defer fh.Close()
	fmt.Fprintf(fh, "// DO NOT EDIT THIS FILE!\n//\n")
	fmt.Fprintf(fh, "// It will be automatically generated by genFont.go\n")
	fmt.Fprintf(fh, "// so your changes will be overwritten.\n\n")
	fmt.Fprintf(fh, "package ledgrid\n\n")
	fmt.Fprintf(fh, "import (\n")
	fmt.Fprintf(fh, "    \"image\"\n")
	fmt.Fprintf(fh, "    \"golang.org/x/image/font/basicfont\"\n")
	fmt.Fprintf(fh, ")\n\n")
	fmt.Fprintf(fh, "var %s = &basicfont.Face{\n", newName)
	fmt.Fprintf(fh, "    Advance: %d,\n", factor*face.Advance)
	fmt.Fprintf(fh, "    Width:   %d,\n", factor*face.Width)
	fmt.Fprintf(fh, "    Height:  %d,\n", factor*face.Height)
	fmt.Fprintf(fh, "    Ascent:  %d,\n", factor*face.Ascent)
	fmt.Fprintf(fh, "    Descent: %d,\n", factor*face.Descent)
	fmt.Fprintf(fh, "    Mask:    mask%s,\n", newName)
	fmt.Fprintf(fh, "    Ranges:  glyphRangeFull,\n")
	fmt.Fprintf(fh, "}\n\n")
	fmt.Fprintf(fh, "var mask%s = &image.Alpha{\n", newName)
	fmt.Fprintf(fh, "    Stride: %d,\n", factor*width)
	fmt.Fprintf(fh, "    Rect:   image.Rectangle{Max: image.Point{%d, %d}},\n",
		factor*mask.Rect.Max.X, factor*mask.Rect.Max.Y)
	fmt.Fprintf(fh, "    Pix: []byte{\n")
	idx := 0
	for idx < len(mask.Pix) {
		row := mask.Pix[idx : idx+mask.Stride : idx+mask.Stride]
		for range factor {
			fmt.Fprintf(fh, "        ")
			for _, val := range row {
				for range factor {
					fmt.Fprintf(fh, "0x%02x, ", val)
				}
			}
			fmt.Fprintf(fh, "\n")
		}
		idx += mask.Stride
		if idx%(height*width) == 0 {
			fmt.Fprintf(fh, "\n")
		}
	}
	fmt.Fprintf(fh, "    },\n")
	fmt.Fprintf(fh, "}\n")
}

// This function can be used to produce a new fixed font by scaling an existing
// fixed font. Scaling factors can only be positive integers.
// func BlowupFixedFont(face *basicfont.Face, newName string) {
// 	width := face.Width
// 	height := face.Ascent
// 	mask := face.Mask.(*image.Alpha)
// 	fileName := fmt.Sprintf("font%s.go", newName)
// 	fh, err := os.Create(fileName)
// 	if err != nil {
// 		log.Fatalf("Couldn't create file: %v", err)
// 	}
// 	defer fh.Close()
// 	fmt.Fprintf(fh, "// DO NOT EDIT THIS FILE!\n//\n")
// 	fmt.Fprintf(fh, "// It will be automatically generated by genFont.go\n")
// 	fmt.Fprintf(fh, "// so your changes will be overwritten.\n\n")
// 	fmt.Fprintf(fh, "package ledgrid\n\n")
// 	fmt.Fprintf(fh, "import (\n")
// 	fmt.Fprintf(fh, "    \"image\"\n")
// 	fmt.Fprintf(fh, "    \"golang.org/x/image/font/basicfont\"\n")
// 	fmt.Fprintf(fh, ")\n\n")
// 	fmt.Fprintf(fh, "var %s = &basicfont.Face{\n", newName)
// 	fmt.Fprintf(fh, "    Advance: %d,\n", 2*face.Advance-1)
// 	fmt.Fprintf(fh, "    Width:   %d,\n", 2*width-1)
// 	fmt.Fprintf(fh, "    Height:  %d,\n", 2*face.Height-1)
// 	fmt.Fprintf(fh, "    Ascent:  %d,\n", 2*height-1)
// 	fmt.Fprintf(fh, "    Descent: %d,\n", 2*face.Descent)
// 	fmt.Fprintf(fh, "    Mask:    mask%s,\n", newName)
// 	fmt.Fprintf(fh, "    Ranges:  glyphRangeFull,\n")
// 	fmt.Fprintf(fh, "}\n\n")
// 	fmt.Fprintf(fh, "var mask%s = &image.Alpha{\n", newName)
// 	fmt.Fprintf(fh, "    Stride: %d,\n", 2*width-1)
// 	fmt.Fprintf(fh, "    Rect:   image.Rectangle{Max: image.Point{%d, %d * numGlyphs}},\n",
// 		2*width-1, 2*height-1)
// 	fmt.Fprintf(fh, "    Pix: []byte{\n")

//     var val uint8
// 	for glyphIdx := range numGlyphs {
// 		for rowIdx := range 2*height - 1 {
// 			fmt.Fprintf(fh, "        ")
// 			oldRowIdx := (glyphIdx * height) + (rowIdx / 2)
// 			if rowIdx%2 == 0 { // we are on a row with original pixels
// 				for colIdx := range 2*width - 1 {
// 					oldColIdx := colIdx / 2
// 					if colIdx%2 == 0 { // we are on a original pixel
// 						val = mask.AlphaAt(oldColIdx, oldRowIdx).A
// 					} else { // we are horizontally between original pixels
// 						val = mask.AlphaAt(oldColIdx, oldRowIdx).A/2 +
// 							mask.AlphaAt(oldColIdx+1, oldRowIdx).A/2
// 					}
// 					fmt.Fprintf(fh, "0x%02x, ", val)
// 				}
// 				fmt.Fprintf(fh, "\n")
// 			} else { // we are on a row with only interpol pixels
// 				for colIdx := range 2*width - 1 {
// 					oldColIdx := colIdx / 2
// 					if colIdx%2 == 0 { // we are vertically between original pixels
// 						val = mask.AlphaAt(oldColIdx, oldRowIdx).A/2 +
// 							mask.AlphaAt(oldColIdx, oldRowIdx+1).A/2
// 					} else { // we are in the middle of four original pixels
// 						val = mask.AlphaAt(oldColIdx, oldRowIdx).A/4 +
// 							mask.AlphaAt(oldColIdx, oldRowIdx+1).A/4 +
// 							mask.AlphaAt(oldColIdx+1, oldRowIdx).A/4 +
// 							mask.AlphaAt(oldColIdx+1, oldRowIdx+1).A/4
// 					}
// 					fmt.Fprintf(fh, "0x%02x, ", val)
// 				}
// 				fmt.Fprintf(fh, "\n")
// 			}
// 		}
// 		fmt.Fprintf(fh, "\n")
// 	}
// 	fmt.Fprintf(fh, "    },\n")
// 	fmt.Fprintf(fh, "}\n")
// }
