#!/usr/bin/bash

if [[ $(whoami) != "root" ]]; then
    echo "You must be root in order to run this script!"
    exit 1
fi

BIN_DIR=/usr/local/sbin
ETC_DIR=/etc/systemd/system

systemctl stop grid-controller

cp gridController $BIN_DIR
cp systemd/grid-controller.service $ETC_DIR

systemctl daemon-reload
systemctl start grid-controller


