#!/usr/bin/bash

if [[ $(whoami) != "root" ]]; then
    echo "You must be root in order to run this script!"
    exit 1
fi

BIN_DIR=/usr/local/sbin
ETC_DIR=/etc/systemd/system

echo "Stopping old GridController..."
systemctl stop grid-controller

echo "Copy new files to system..."
cp gridController $BIN_DIR
cp systemd/grid-controller.service $ETC_DIR

echo "Reload configuration files..."
systemctl daemon-reload
echo "Start new GridController..."
systemctl start grid-controller

echo "We are done!"

