#!/usr/bin/bash

if [[ $(whoami) != "root" ]]; then
    echo "You must be root in order to run this script!"
    exit 1
fi

DST_DIR=/usr/local/sbin

systemctl stop grid-controller
cp gridController $DST_DIR
systemctl start grid-controller


